// Supabase configuration
window.SUPABASE_CONFIG={url:"https://lllxrjqwmsrapuwkgxdy.supabase.co",anonKey:"sb_publishable_5ixnQl8DbYYZ7juw5oO-MQ_QoB_kwRT"};
(function(){const friendly={"maximum attempts reached":"🚫 Bạn đã hết số lần làm bài. Vui lòng liên hệ giáo viên nếu cần được hỗ trợ.","exam is closed or not available":"🔒 Đề thi hiện đã đóng hoặc không còn khả dụng.","exam is not available yet":"⏰ Chưa đến thời gian thi. Vui lòng quay lại sau.","exam has ended":"⏰ Thời gian thi của đề đã kết thúc.","not allowed":"🚫 Bạn không được phép thực hiện thao tác này.","invalid exam":"❌ Đề thi không hợp lệ hoặc không tồn tại.","student login required":"🔐 Vui lòng đăng nhập tài khoản sinh viên trước khi truy cập bài kiểm tra.","invalid api key":"❌ Khóa kết nối Supabase không hợp lệ. Vui lòng tải lại trang."};const oldAlert=window.alert;window.alert=function(message){const s=String(message||""),low=s.toLowerCase();let out=null;for(const k in friendly)if(low.includes(k)){out=friendly[k];break}oldAlert.call(window,out||message)}})();
(function(){if(!/student\.html$/.test(location.pathname))return;const add=(id,src)=>{if(document.getElementById(id))return;const s=document.createElement('script');s.id=id;s.src=src;s.defer=true;document.head.appendChild(s)};add('student-auth-script','./student-auth.js?v=10');add('student-history-auth-script','./student-history-auth.js?v=8');add('student-reading-route-script','./student-reading-route.js?v=6');add('student-writing-route-script','./student-writing-route.js?v=6');add('student-listening-review-fix-script','./student-listening-review-fix.js?v=4');add('student-submit-optional-mssv-script','./student-submit-optional-mssv.js?v=4')})();
(function(){if(!/reading\.html$/.test(location.pathname))return;const add=(id,src)=>{if(document.getElementById(id))return;const s=document.createElement('script');s.id=id;s.src=src;s.defer=true;document.head.appendChild(s)};add('student-reading-fix-script','./student-reading-fix.js?v=10');add('student-reading-direct-fix-script','./student-reading-direct-fix.js?v=5');add('student-auth-reading-script','./student-auth.js?v=10');add('reading-student-runtime-script','./reading-student-runtime.js?v=3');add('reading-query-rich-fix-script','./reading-query-rich-fix.js?v=2');add('reading-review-fix-script','./reading-review-fix.js?v=2')})();
(function(){if(!/results\.html$/.test(location.pathname))return;const add=(id,src)=>{if(document.getElementById(id))return;const s=document.createElement('script');s.id=id;s.src=src;s.defer=true;document.head.appendChild(s)};add('results-delete-script','./results-delete.js?v=1');add('results-recovery-script','./results-recovery.js?v=1')})();
(function(){if(!/manage\.html$/.test(location.pathname))return;const add=(id,src)=>{if(document.getElementById(id))return;const s=document.createElement('script');s.id=id;s.src=src;s.defer=true;document.head.appendChild(s)};add('manage-reading-fix-script','./manage-reading-fix.js?v=2');add('reading-format-fix-script','./reading-format-fix.js?v=4');add('audio-ui-fix-script','./audio-ui-fix.js?v=1');add('word-upload-status-fix-script','./word-upload-status-fix.js?v=1');add('reading-word-format-fix-script','./reading-word-format-fix-v2.js?v=2');add('reading-word-alignment-fix-script','./reading-word-alignment-fix.js?v=1');add('writing-rubric-admin-script','./writing-admin-fix.js?v=5');add('exam-folders-children-fix-script','./exam-folders-children-fix.js?v=14')})();
(function(){const s=document.createElement('script');s.id='english-studio-security';s.src='./security-v4.js?v=3';s.defer=true;document.head.appendChild(s)})();
(function(){const s=document.createElement('script');s.id='auth-ui-fix-script';s.src='./auth-ui-fix.js?v=5';s.defer=true;document.head.appendChild(s)})();
