// English Studio - Exam Library / Folders v3
(function(){
  if(!/manage\.html$/.test(location.pathname)||window.__ENGLISH_STUDIO_EXAM_FOLDERS__)return;
  window.__ENGLISH_STUDIO_EXAM_FOLDERS__=true;
  const cfg=window.SUPABASE_CONFIG||{};
  const db=supabase.createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  let folders=[],exams=[],activeFolder=null,ready=false;
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const parse=v=>{if(Array.isArray(v))return v;if(typeof v==='string')try{return JSON.parse(v)}catch{return[]}return[]};
  const qs=e=>parse(e?.questions);
  function typeName(t){return({listening:'🎧 Listening',reading:'📖 Reading',writing:'✍️ Writing',mixed:'🧩 Kết hợp'})[t]||'🎧 Listening'}
  function status(e){const now=Date.now(),st=e.start_at?new Date(e.start_at).getTime():null,en=e.end_at?new Date(e.end_at).getTime():null;if(!e.published)return['⚪ Đã đóng','off'];if(st&&now<st)return['🕐 Chưa đến giờ','scheduled'];if(en&&now>end)return['🔴 Hết hạn','closed'];return['🟢 Đang mở','']}
  function children(pid){return folders.filter(f=>(f.parent_id||null)===(pid||null)).sort((a,b)=>a.name.localeCompare(b.name,'vi'))}
  function path(id){const a=[];let f=folders.find(x=>x.id===id),n=0;while(f&&n++<50){a.unshift(f);f=folders.find(x=>x.id===f.parent_id)}return a}
  function folderTree(pid=null,depth=0){return children(pid).map(f=>`<button class="ef-folder ${activeFolder===f.id?'active':''}" data-id="${f.id}" style="padding-left:${8+depth*17}px">📁 ${esc(f.name)}</button>${folderTree(f.id,depth+1)}`).join('')}
  function style(){if(document.getElementById('ef-style'))return;const s=document.createElement('style');s.id='ef-style';s.textContent=`.ef-shell{display:grid;grid-template-columns:250px minmax(0,1fr);gap:14px;margin-top:14px}.ef-side,.ef-toolbar{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:13px;box-shadow:0 5px 20px #0f172a0a}.ef-side{height:max-content;position:sticky;top:12px}.ef-side h3{margin:4px 8px 10px}.ef-folder{display:block;width:100%;border:0;background:transparent;text-align:left;border-radius:9px;padding-top:9px;padding-bottom:9px;font:inherit;cursor:pointer;color:#334155}.ef-folder:hover{background:#f1f5f9}.ef-folder.active{background:#dbeafe;color:#1d4ed8;font-weight:800}.ef-side-actions{display:flex;gap:6px;margin-bottom:8px}.ef-side-actions button{flex:1}.ef-toolbar{margin-bottom:12px}.ef-breadcrumb{font-weight:800}.ef-muted{font-size:13px;color:#64748b;margin-top:4px}.ef-exam{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:16px;margin:12px 0;box-shadow:0 5px 20px #0f172a0a}.ef-exam .actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.ef-move{background:#0ea5e9!important}.ef-empty{text-align:center;color:#64748b;padding:28px;background:#fff;border:1px dashed #cbd5e1;border-radius:16px}.ef-menu{display:flex;gap:5px;margin-top:8px}.ef-menu button{border:0;background:#eef2ff;border-radius:8px;padding:6px 8px;cursor:pointer}@media(max-width:760px){.ef-shell{grid-template-columns:1fr}.ef-side{position:static}}`;document.head.appendChild(s)}
  async function load(){
    const session=await db.auth.getSession();
    if(!session.data?.session){ready=false;return}
    const fr=await db.from('exam_folders').select('id,name,parent_id,created_at,updated_at').order('name',{ascending:true});
    if(fr.error){console.error('exam_folders load failed:',fr.error);ready=false;return}
    const er=await db.from('exams').select('*').order('created_at',{ascending:false});
    if(er.error){alert('❌ Không tải được danh sách đề: '+er.error.message);ready=false;return}
    folders=fr.data||[];exams=er.data||[];ready=true;render();
  }
  function card(e){const [st,cl]=status(e),time=(e.start_at?new Date(e.start_at).toLocaleString('vi-VN'):'Ngay lập tức')+' → '+(e.end_at?new Date(e.end_at).toLocaleString('vi-VN'):'Không giới hạn');return `<article class="ef-exam"><div class="row"><div style="min-width:250px;flex:1"><h3 style="margin:0 0 6px">${esc(e.title||'Không tên')} <span class="type">${typeName(e.exam_type)}</span></h3><div class="ef-muted">${qs(e).length} câu • ${e.duration_minutes||0} phút</div><div style="margin-top:8px"><span class="badge ${cl}">${st}</span></div><div class="ef-muted" style="margin-top:7px">🕐 ${esc(time)}</div></div></div><div class="actions"><button class="btn gray" onclick="edit('${e.id}')">✏️ Sửa</button><button class="btn ef-move" onclick="window.__examFolderMove('${e.id}')">📁 Chuyển thư mục</button><button class="btn" onclick="duplicate('${e.id}')">📑 Nhân bản</button><button class="btn orange" onclick="toggle('${e.id}')">${e.published?'🔒 Đóng':'🔓 Mở'}</button><button class="btn purple" onclick="copyLink('${e.id}')">🔗 Link học sinh</button><a class="btn gray" href="./results.html?exam=${encodeURIComponent(e.id)}">📊 Kết quả</a><button class="btn red" onclick="removeExam('${e.id}')">🗑️ Xóa</button></div></article>`}
  function render(){if(!ready)return;const app=document.getElementById('app');if(!app)return;const list=activeFolder===null?exams:activeFolder==='__uncategorized__'?exams.filter(e=>!e.folder_id):exams.filter(e=>e.folder_id===activeFolder);const p=activeFolder&&activeFolder!=='__uncategorized__'?path(activeFolder):[];app.innerHTML=`<div class="row"><div><h2>📚 Thư viện đề</h2><span class="muted">Tổ chức đề theo thư mục để dễ quản lý.</span></div><div class="actions"><a class="btn gray" href="./admin.html">← Dashboard</a><button class="btn" onclick="createExam()">＋ Tạo đề</button></div></div><div class="ef-shell"><aside class="ef-side"><h3>📚 Thư mục</h3><div class="ef-side-actions"><button class="btn small" id="ef-new">＋ Thư mục</button><button class="btn gray small" id="ef-reload">↻</button></div><button class="ef-folder ${activeFolder===null?'active':''}" data-id="__all__">📚 Tất cả đề</button>${folderTree()}<button class="ef-folder ${activeFolder==='__uncategorized__'?'active':''}" data-id="__uncategorized__">📄 Chưa phân loại</button></aside><section><div class="ef-toolbar"><div class="ef-breadcrumb">📚 Thư viện${p.map(f=>` › 📁 ${esc(f.name)}`).join('')}${activeFolder==='__uncategorized__'?' › 📄 Chưa phân loại':''}</div><div class="ef-muted">${list.length} đề trong mục này • Tổng ${exams.length} đề</div>${activeFolder&&activeFolder!=='__uncategorized__'?`<div class="ef-menu"><button onclick="window.__examFolderRename('${activeFolder}')">✏️ Đổi tên</button><button onclick="window.__examFolderDelete('${activeFolder}')">🗑️ Xóa thư mục</button><button onclick="window.__examFolderNew('${activeFolder}')">＋ Thư mục con</button></div>`:''}</div><div id="ef-list">${list.length?list.map(card).join(''):`<div class="ef-empty">Thư mục này chưa có đề.<br><br><button class="btn" onclick="createExam()">＋ Tạo đề</button></div>`}</div></section></div>`;app.querySelectorAll('.ef-folder').forEach(b=>b.onclick=()=>{const id=b.dataset.id;activeFolder=id==='__all__'?null:id;render()});document.getElementById('ef-new').onclick=()=>newFolder(activeFolder&&activeFolder!=='__uncategorized__'?activeFolder:null);document.getElementById('ef-reload').onclick=load}
  async function sessionUid(){const r=await db.auth.getSession();return r.data?.session?.user?.id||null}
  async function newFolder(parentId=null){const uid=await sessionUid();if(!uid)return alert('🔐 Phiên đăng nhập đã hết hạn.');const n=prompt(parentId?'Tên thư mục con:':'Tên thư mục mới:');if(n===null)return;const name=n.trim();if(!name)return alert('Tên thư mục không được để trống.');const r=await db.from('exam_folders').insert({owner_id:uid,parent_id:parentId,name}).select().single();if(r.error)return alert('❌ '+r.error.message);activeFolder=r.data.id;await load()}
  async function renameFolder(id){const f=folders.find(x=>x.id===id);if(!f)return;const n=prompt('Tên mới:',f.name);if(n===null)return;const name=n.trim();if(!name)return;const r=await db.from('exam_folders').update({name,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)alert('❌ '+r.error.message);else await load()}
  async function deleteFolder(id){const f=folders.find(x=>x.id===id);if(!f)return;const count=exams.filter(e=>e.folder_id===id).length,child=folders.filter(x=>x.parent_id===id).length;if(!confirm(`Xóa thư mục "${f.name}"?${count?'\n'+count+' đề sẽ chuyển về Chưa phân loại.':''}${child?'\nCác thư mục con cũng sẽ bị xóa.':''}`))return;const r=await db.from('exam_folders').delete().eq('id',id);if(r.error)alert('❌ '+r.error.message);else{activeFolder=null;await load()}}
  async function moveExam(id){const e=exams.find(x=>x.id===id);if(!e)return;const opts=['__none__|📄 Chưa phân loại'].concat(folders.map(f=>`${f.id}|${'— '.repeat(Math.max(0,path(f.id).length-1))}📁 ${f.name}`));const text=opts.map((x,i)=>`${i}. ${x.split('|')[1]}`).join('\n');const a=prompt('Chọn thư mục bằng số:\n'+text,'0');if(a===null)return;const n=Number(a);if(!Number.isInteger(n)||!opts[n])return alert('❌ Lựa chọn không hợp lệ.');const id2=opts[n].split('|')[0];const r=await db.from('exams').update({folder_id:id2==='__none__'?null:id2}).eq('id',id);if(r.error)alert('❌ '+r.error.message);else await load()}
  window.__examFolderNew=newFolder;window.__examFolderRename=renameFolder;window.__examFolderDelete=deleteFolder;window.__examFolderMove=moveExam;
  async function boot(){style();await load();if(!ready){const app=document.getElementById('app');if(app){const old=app.querySelector('.notice.warn');if(old)old.remove();const n=document.createElement('div');n.className='notice warn';n.innerHTML='📁 <b>Quản lý thư mục chưa được bật.</b> Hãy đăng nhập lại giảng viên rồi tải lại trang.';app.prepend(n)}}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
