/* English Studio - student Writing runtime */
(function(){
const cfg=window.SUPABASE_CONFIG||{};const sb=supabase.createClient(cfg.url,cfg.anonKey);const app=document.getElementById('app');let exam=null,timer=null,draftKey='';
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const words=s=>String(s||'').trim()?String(s).trim().split(/\s+/).length:0;const id=()=>new URLSearchParams(location.search).get('exam');const back=()=>location.href='./student.html';
const parse=v=>{if(Array.isArray(v))return v;if(typeof v==='string'){try{return JSON.parse(v)}catch{return []}}if(v&&typeof v==='object')return Object.values(v);return []};
const fmt=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
function normalize(v){if(Array.isArray(v))return v[0]||null;if(v?.data&&Array.isArray(v.data))return v.data[0]||null;if(typeof v==='string'){try{return normalize(JSON.parse(v))}catch{return null}}return v||null}
function safePrompt(v){const raw=String(v??'');if(!/<[a-z][\s\S]*>/i.test(raw))return esc(raw).replace(/\n/g,'<br>');const doc=new DOMParser().parseFromString(raw,'text/html');doc.querySelectorAll('script,style,iframe,object,embed,form').forEach(x=>x.remove());doc.body.querySelectorAll('*').forEach(el=>{[...el.attributes].forEach(a=>{if(/^on/i.test(a.name)||a.name==='style'&&/url\s*\(/i.test(a.value))el.removeAttribute(a.name)});if(el.tagName==='A'&&!/^https?:|^mailto:/i.test(el.getAttribute('href')||''))el.removeAttribute('href')});return doc.body.innerHTML||esc(raw)}
async function load(){
 if(!id()){app.innerHTML='<div class="card">❌ Thiếu mã đề. <button class="btn gray" onclick="back()">← Quay lại</button></div>';return}
 const {data:{session}}=await sb.auth.getSession();if(!session){location.href='./student.html';return}
 let r=await sb.rpc('get_writing_exam_for_student_v2',{p_exam_id:id()});let data=!r.error?normalize(r.data):null;
 if(!data){r=await sb.rpc('get_writing_exam_for_student',{p_exam_id:id()});data=!r.error?normalize(r.data):null}
 if(!data){r=await sb.rpc('get_exam_for_student',{p_exam_id:id()});data=!r.error?normalize(r.data):null}
 if(!data||String(data.exam_type||'').toLowerCase()!=='writing'){app.innerHTML=`<div class="card"><h2>❌ Không tải được đề Writing</h2><p>${esc(r?.error?.message||'Đề không tồn tại, chưa được công khai hoặc dữ liệu Writing chưa được trả về từ Supabase.')}</p><button class="btn gray" onclick="back()">← Quay về thư viện</button></div>`;return}
 exam=data;draftKey=`english-studio-writing-draft-${exam.id}-${session.user.id}`;render()
}
function render(){
 const qs=parse(exam.questions),p=exam.writing_prompt||exam.description||'';const min=qs.find(q=>q?.min_words)?.min_words||0,max=qs.find(q=>q?.max_words)?.max_words||0;const saved=localStorage.getItem(draftKey)||'',duration=Math.max(1,Number(exam.duration_minutes||60));
 if(!p){app.innerHTML='<div class="card"><h2>⚠️ Đề Writing chưa có nội dung</h2><p>Giảng viên cần nhập Đề bài Writing trước khi sinh viên làm bài.</p><button class="btn gray" onclick="back()">← Quay về thư viện đề</button></div>';return}
 app.innerHTML=`<div class="bar"><button class="btn gray" onclick="back()">← Quay về thư viện đề</button><span id="timer" class="muted">✍️ Writing • ⏱️ ${fmt(duration*60)}</span></div><div class="card"><h2>${esc(exam.title)}</h2><div class="prompt"><b>📌 Đề bài</b><div class="formatted-prompt" style="margin-top:8px">${safePrompt(p)}</div>${min||max?`<p class="muted">Yêu cầu: ${min?'tối thiểu '+min+' từ':''}${min&&max?' • ':''}${max?'tối đa '+max+' từ':''}</p>`:''}</div></div><div class="card"><div class="bar"><b>📝 Bài viết của bạn</b><span id="wordCount" class="muted">${words(saved)} từ</span></div><textarea id="essay" class="writing-box" placeholder="Nhập bài viết của bạn tại đây...">${esc(saved)}</textarea><div class="bar" style="margin-top:14px"><span class="muted">💾 Bài viết được lưu nháp trên thiết bị khi bạn nhập.</span><button id="submit" class="btn" onclick="submitWriting()">📤 Nộp bài & chấm AI</button></div></div><div id="result"></div>`;
 const ta=document.getElementById('essay');ta.addEventListener('input',()=>{document.getElementById('wordCount').textContent=words(ta.value)+' từ';localStorage.setItem(draftKey,ta.value)});let left=duration*60;clearInterval(timer);timer=setInterval(()=>{left--;const el=document.getElementById('timer');if(left<=0){clearInterval(timer);el.textContent='⏰ Hết giờ';submitWriting(true);return}el.textContent=`✍️ Writing • ⏱️ ${fmt(left)}`},1000)
}
async function submitWriting(auto=false){const ta=document.getElementById('essay'),btn=document.getElementById('submit'),essay=ta.value.trim();if(!essay){alert('❌ Bạn chưa nhập bài viết.');return}const count=words(essay),qs=parse(exam.questions),min=qs.find(q=>q?.min_words)?.min_words||0;if(min&&count<Number(min)){alert(`❌ Bài viết chưa đủ ${min} từ. Hiện tại: ${count} từ.`);return}btn.disabled=true;btn.textContent='⏳ AI đang chấm bài...';try{const {data:{session}}=await sb.auth.getSession();if(!session)throw new Error('Student login required');const r=await fetch(`${cfg.url}/functions/v1/dynamic-api`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`,apikey:cfg.anonKey},body:JSON.stringify({exam_id:exam.id,essay})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={error:text}}if(!r.ok){const detail=data.detail?`\n\nChi tiết: ${data.detail}`:'';throw new Error((data.error||data.message||`HTTP ${r.status}`)+detail)}localStorage.removeItem(draftKey);showResult(data)}catch(e){alert('❌ '+e.message);btn.disabled=false;btn.textContent='📤 Nộp bài & chấm AI'}}
function list(a){return(Array.isArray(a)?a:[]).map(x=>`<li>${esc(x)}</li>`).join('')}
function rubricForResult(){const source=exam?.writing_rubric??exam?.rubric??exam?.criteria??[];return parse(source).map(x=>({name:String(x?.name??x?.title??'').trim(),max:Number(x?.max??x?.max_score??x?.score??x?.points??0)})).filter(x=>x.name&&Number.isFinite(x.max)&&x.max>0)}
function showResult(r){clearInterval(timer);document.getElementById('essay').disabled=true;document.getElementById('submit').style.display='none';const rubric=rubricForResult();const rawScores=r.rubric_scores&&typeof r.rubric_scores==='object'?r.rubric_scores:{};const scores=rubric.length?rubric.map(x=>({name:x.name,max:x.max,value:Number(rawScores[x.name]??0)})):Object.entries(rawScores).map(([name,value])=>({name,max:null,value:Number(value)}));const total=Number(r.total_score??0);const rubricHtml=scores.map(x=>`<div class="rubric-row"><span class="rubric-name">${esc(x.name)}</span><strong>${esc(x.value)}</strong><span class="rubric-max">/${x.max!==null?esc(x.max):'?'}</span></div>`).join('');document.getElementById('result').innerHTML=`<div class="card"><div class="bar"><div><h2>🎉 Kết quả chấm AI</h2><p class="muted">${esc(r.word_count)} từ • Mô hình: ${esc(r.ai_model||'AI')}</p></div><div class="score">${esc(total)}/10</div></div><div class="rubric-result"><div class="rubric-title">📊 Điểm theo tiêu chí</div>${rubricHtml}<div class="rubric-total"><span>Tổng</span><strong>${esc(total)}/10</strong></div></div><div class="feedback"><b>💬 Nhận xét tổng quan</b><p>${esc(r.overall_comment||'')}</p></div><div class="feedback ok"><b>💪 Điểm mạnh</b><ul>${list(r.strengths)}</ul></div><div class="feedback"><b>🎯 Cần cải thiện</b><ul>${list(r.improvements)}</ul></div>${(r.grammar_errors||[]).length?`<div class="feedback error"><b>🔎 Lỗi cần chú ý</b>${r.grammar_errors.map(x=>`<p><b>${esc(x.original)}</b> → <b>${esc(x.correction)}</b><br>${esc(x.explanation)}</p>`).join('')}</div>`:''}${(r.better_phrases||[]).length?`<div class="feedback"><b>✨ Gợi ý diễn đạt tốt hơn</b>${r.better_phrases.map(x=>`<p>${esc(x.original)} → <b>${esc(x.better)}</b></p>`).join('')}</div>`:''}<button class="btn gray" onclick="back()">← Về thư viện đề</button></div>`}
window.back=back;window.submitWriting=submitWriting;load();
})();